### ISSUE TITLE
Some deprecations

### ISSUE THREAD

**Issue by arch-alam** [chadmcrowell/CKA-Exercises#5]
- https://github.com/chadmcrowell/CKA-Exercises/blob/master/core_concepts.md#output-a-pods-yaml-without-cluster-specific-information

--export option has been deprecated in version 1.14 and removed in version 1.18.

- https://github.com/chadmcrowell/CKA-Exercises/blob/master/core_concepts.md#get-the-status-of-the-control-plane-components

ComponentStatus is deprecated in v1.19+

Alternatives: 
curl -k https://localhost:6443/livez?verbose
curl -k https://localhost:6443/readyz?verbose
Curl -k https://localhost:6443/healthz?verbose
		     
One last thing:	     
https://github.com/chadmcrowell/CKA-Exercises/blob/master/core_concepts.md#set-a-context-utilizing-a-specific-username-and-namespace

kubectl config use-context gce ------> Not needed

**Comment by chadmcrowell** [comment]
Thanks @kmmitul ! I have fixed all the deprecations that you pointed out!
